// Configurable song pool for Music Bingo. Each entry is
// { song, artist, year? } — `year` is optional and the game must render
// correctly whether or not it's present. This is the initial test dataset;
// it's intentionally larger than the configured grid so a board can be
// randomly (and uniquely) selected from it.
export const songs = [
  { song: "Friday I'm In Love", artist: "The Cure" },
  { song: "Leave The Door Open", artist: "Bruno Mars" },
  { song: "Back On 74", artist: "Jungle" },
  { song: "Take on Me", artist: "a-ha" },
  { song: "Billie Jean", artist: "Michael Jackson" },
  {
    song: "Some Velvet Morning (feat. Kate Moss) - Single Mix - Remastered 2019",
    artist: "Primal Scream",
  },
  { song: "Para Siempre", artist: "Benjamín Amadeo" },
  { song: "Ice Ice Baby", artist: "Vanilla Ice" },
  { song: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd" },
  { song: "Private Idaho", artist: "The B-52's" },
  { song: "Parque de Diversiones 15 Años", artist: "Hana" },
  { song: "WHERE IS MY HUSBAND!", artist: "RAYE" },
  { song: "Water", artist: "Tyla" },
  { song: "CHANEL", artist: "Tyla" },
  { song: "Mercy", artist: "Duffy" },
  {
    song: "Have You Ever Seen The Rain",
    artist: "Creedence Clearwater Revival",
  },
  { song: "Hooked On A Feeling", artist: "Blue Swede" },
  { song: "Spirit In The Sky", artist: "Norman Greenbaum" },
  { song: "No One Dies From Love", artist: "Tove Lo" },
  { song: "Fooled Around And Fell In Love", artist: "Elvin Bishop" },
  { song: "Everybody Wants To Rule The World", artist: "Tears For Fears" },
  { song: "Dice Lo Que Siente", artist: "Miranda!" },
  { song: "Romix", artist: "Miranda!" },
  { song: "Amour Ex Machina", artist: "L'Impératrice" },
  { song: "Cosmogonie", artist: "L'Impératrice" },
  { song: "Feet Don't Fail Me Now", artist: "Joy Crookes" },
  {
    song: "Sweet & Sublime (feat. Erick the Architect)",
    artist: "L'Impératrice",
  },
  { song: "ENTROPIA", artist: "L'Impératrice" },
  { song: "Unstoppable", artist: "Lianne La Havas" },
  { song: "telepatía", artist: "Kali Uchis" },
  { song: "Me Gustas Tanto", artist: "Miranda!" },
  { song: "Como Eran Las Cosas", artist: "Babasonicos" },
  { song: "Dancing With A Stranger (with Normani)", artist: "Sam Smith" },
  { song: "Todo de Mi", artist: "Angela Navarro" },
  { song: "Angels Like You", artist: "Miley Cyrus" },
  { song: "Extraño", artist: "Miranda!" },
  { song: "Hasta el fin del mundo", artist: "Jennifer Peña" },
  { song: "Freed From Desire", artist: "Gala" },
  { song: "100% Pure Love", artist: "Crystal Waters" },
  { song: "Smooth Operator - Single Version", artist: "Sade" },
  { song: "Mismo Amor", artist: "Julieta Venegas" },
  { song: "Please Me", artist: "Poncho" },
  { song: "Anxiety", artist: "Doechii" },
  { song: "Rude Boy", artist: "Rihanna" },
  { song: "Pumped Up Kicks", artist: "Foster The People" },
  { song: "Ángel - Once in Your Lifetime", artist: "Belinda" },
  { song: "Messy", artist: "Lola Young" },
  { song: "Move", artist: "Adam Port" },
  { song: "F.E.E.L. - Angelo Ferreri Remix", artist: "Music P" },
  {
    song: "World Hold On (Children Of The Sky) - FISHER Rework",
    artist: "Bob Sinclar",
  },
  { song: "Putita", artist: "Babasonicos" },
  { song: "Vámonos De Viaje", artist: "Bandalos Chinos" },
  { song: "BIRDS OF A FEATHER", artist: "Billie Eilish" },
  { song: "The Door", artist: "Teddy Swims" },
  { song: "Lose Control", artist: "Teddy Swims" },
  { song: "Será", artist: "Las Pelotas" },
  { song: "La Pregunta", artist: "Babasonicos" },
  { song: "El Mareo", artist: "Bajofondo" },
  { song: "Carismático", artist: "Babasonicos" },
  { song: "Die With A Smile", artist: "Lady Gaga" },
  { song: "Don't Speak", artist: "No Doubt" },
  { song: "El Colmo", artist: "Babasonicos" },
  { song: "Zombie", artist: "The Cranberries" },
  { song: "Flowers", artist: "Miley Cyrus" },
  { song: "Anubis", artist: "Babasonicos" },
  { song: "Break Free", artist: "Ariana Grande" },
  { song: "Blinding Lights", artist: "The Weeknd" },
  { song: "Golden", artist: "Harry Styles" },
  { song: "love nwantiti (feat. Dj Yo! & AX'EL) - Remix", artist: "CKay" },
  { song: "positions", artist: "Ariana Grande" },
  { song: "Miranda Mix (Oíd Mortales Mix)", artist: "Miranda!" },
  { song: "Supalonely", artist: "BENEE" },
  { song: "Watermelon Sugar", artist: "Harry Styles" },
  { song: "Smile", artist: "Lily Allen" },
  { song: "Chained To The Rhythm", artist: "Katy Perry" },
  { song: "What's Up?", artist: "4 Non Blondes" },
  { song: "Take Me To Church", artist: "Hozier" },
  { song: "Tú", artist: "Shakira" },
  { song: "Personal Jesus", artist: "Depeche Mode" },
  { song: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers" },
  { song: "This Is What You Came For", artist: "Calvin Harris" },
  { song: "Send My Love (To Your New Lover)", artist: "Adele" },
  { song: "Price Tag - Acoustic Version", artist: "Jessie J" },
  { song: "Sexmachine (Part 1 And 2)", artist: "James Brown" },
  { song: "Elastic Heart", artist: "Sia" },
  { song: "Back To Black", artist: "Amy Winehouse" },
  { song: "You Know I'm No Good", artist: "Amy Winehouse" },
  { song: "Rehab", artist: "Amy Winehouse" },
  { song: "Amiga da Minha Mulher", artist: "Seu Jorge" },
];
